from .cliente import Cliente
from .lanche import Lanche
from .pedido import Pedido
from .salgado import Salgado
from .pedido_info import PedidoInfo
from .item_pedido import ItemPedido
from .prato import Prato
from .info_item_pedido import InfoItemPedido
from .pizza import Pizza
from .adm import Adm
