from .repositorio import Repositorio
from .repositorio_item_pedido import RepositorioItemPedido
from .repositorio_pizza import RepositorioPizza
from .repositorio_lanche import RepositorioLanche
from .repositorio_prato import RepositorioPrato
from .repositorio_salgado import RepositorioSalgado
from .repositorio_pedido import RepositorioPedido
from .repositorio_cliente import RepositorioCliente
from .repositorio_adm import RepositorioAdm
